### ISSUE TITLE
。。。研究了半天不会用这个配置

### ISSUE THREAD

**Issue by obrua** [muyuuuu/My-Next-Theme-Blog-Config-Files#2]
能否写个教程

**Comment by muyuuuu** [comment]
> 能否写个教程

就是网上教程太多了，所以我才没写教程。你先查『hexo如何使用next』，这一步完成后，不要改任何样式配置。然后，按着[这个方法](https://github.com/theme-next/hexo-theme-next/blob/master/docs/DATA-FILES.md)修改样式（如果是 next 主题，建议用第二个方法），这里用我的文件是可以的。
